services:
  extention:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: extention
    volumes:
      - ./extention:/app
    # command: "bun run dev"
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
